# titre

## Exo 1

In [32]:
import numpy as np

a = np.arange(10 + 1)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Exo 2

In [19]:
import numpy as np

a = np.linspace(0, 1, 5)
a


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Exo 3

In [36]:
T = np.array([5,2,8,17,6,14])
T = np.sum(T)
print(T)

52


## Exo 4

Le code suivant utilise la fonction numpy.dot() pour calculer le produit scalaire de deux tableaux ou vecteurs en Python.

In [34]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

loulou = np.dot(a, b)
loulou

30

## Exo 6

In [35]:
import numpy as np

a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
sorted_array = np.sort(a)

print("Sorted array: ", sorted_array)

Sorted array:  [ 1  2  2  3  4  6  8  9 23 33 54 54 55 77 86 89]


## Exo 7

In [52]:
import numpy as np

a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
sorted_array = np.min(a)
sorted1 = np.max(a)
sorted2 = np.mean(a)
sorted3 = np.median(a)
sortedT = np.std(a)
print("La valeur min is: ", sorted_array, "--  la valeur max is :", sorted1, "--  La moyenne is: ", sorted2, "--  La mediane is: ", sorted3, "--  l'ecart type is:", sortedT, "ma grosse pucinette"   )



La valeur min is:  1 --  la valeur max is : 89 --  La moyenne is:  31.625 --  La mediane is:  16.0 --  l'ecart type is: 31.557239660654734 ma grosse pucinette


## Exo 8

In [61]:
a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
1*(a>5)


array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0])

la solution est telle => car une codition renvoie forcement un boolean ex: 

a>5 
array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False])

Alors que 1*(a>5) renvoie 0 (if la condition est False) et 1 (if la condition est True)

In [59]:
1 * (a>5)

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0])

In [56]:
a[a>5]= 10
a

array([ 1,  2, 10, 10, 10, 10, 10, 10, 10, 10,  2,  3, 10, 10, 10,  4])

## Exo 9

In [45]:
import numpy as np 

np.random.randint(0,11, size=(3,10))



array([[ 7,  2,  5,  7,  0,  3,  0,  1,  8,  2],
       [ 5,  0, 10,  5,  1,  9,  4,  2,  7,  2],
       [ 0,  5,  4,  6,  8,  6,  0,  8,  3,  9]])

## Exo 10 Trouver la valeur max 

In [3]:
import numpy as np

a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
max = None

for i in a:
    if (max is None or i > max):
        max = i 
print("La plus grande valeur du tableau est : ", max)

La plus grande valeur du tableau est :  89


## Exo 11 Trouver la valeur min

In [9]:
import numpy as np

a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
min = None

for i in a:
    if (min is None or i < min):
        min = i
print("la valeur minimum est :", min)

la valeur minimum est : 1


In [26]:
np.random.rand()


0.36270759411177544

In [41]:
import numpy as np

np.random.randint(5, size=(2, 4))


array([[4, 1, 1, 4],
       [4, 4, 0, 3]])

## Loto tricks**?

In [47]:
import numpy as np 

np.random.randint(1,50, size=(7,1000))

array([[44,  7, 27, ..., 48, 29, 41],
       [17,  5, 15, ..., 21, 45,  6],
       [10, 29, 24, ..., 40, 39,  3],
       ...,
       [14,  9, 15, ..., 46, 40, 17],
       [36, 19, 46, ..., 21, 36, 40],
       [ 8, 41,  4, ..., 47, 31, 18]])