## Générateur de nombre aléatoire

In [52]:
import numpy as np

# créer une liste de numéro random entre 1 et 49 (loto)
l2 =  np.random.choice((np.arange(1,49)), 5, replace=False)
print(l2)
NG= np.random.choice((np.arange(1,10)), 1, replace=False)
print(NG)



[19 38 12 24  3]
[190 380 120 240  30]
[5]


In [48]:
import numpy as np

l2 = np.random.choice((np.arange(1,50)), 7, replace=False)
print(l2)

NG= np.random.choice((np.arange(1,10)), 2, replace=False)
print(NG)


[38 13  9 16 41 30  6]
[2 6]


In [53]:
import numpy as np
import matplotlib.pyplot as plt

num_simulations = 1000
num_draws = 5
min_value = 1
max_value = 49

# Génère les 1000 séries de tirages d'array de 5 nb entre 1 et 49
all_draws = np.random.randint(min_value, max_value + 1, size=(num_simulations, num_draws))

In [55]:
#choisir le nombre souhaité entre 1 et 49
target_number = 25
occurrences = np.sum(all_draws == target_number)
print(occurrences)


probability = occurrences / num_simulations
print(probability)


109
0.109


In [3]:
import numpy as np
import matplotlib.pyplot as plt

# Génère les 1000 séries de tirages
num_simulations = 7
num_draws = 5
min_value = 1
max_value = 49
all_draws = np.random.randint(min_value, max_value + 1, size=(num_simulations, num_draws))

# Calcule les probabilités pour chaque nombre de 1 à 50
probabilities = []
for target_number in range(1, 49):
    occurrences = np.sum(all_draws == target_number)
    probability = occurrences / num_simulations
    probabilities.append(probability)
    





In [5]:
import numpy as np

# Paramètres
min_value = 1
max_value = 49
num_simulations = 10000
num_draws = 5

# Génère les 1000 séries de tirages
all_draws = np.random.randint(min_value, max_value + 1, size=(num_simulations, num_draws))

# Initialisation des tableaux
numbers = list(range(min_value, max_value + 1))
occurrences = []
probabilities = []

# Calcul des occurrences et des probabilités
for target_number in numbers:
    occurrences_count = np.sum(all_draws == target_number)
    probability = occurrences_count / num_simulations
    
    occurrences.append(occurrences_count)
    probabilities.append(probability)

# Crée un tableau avec les valeurs
data_table = {
    'Number': numbers,
    'Occurrences': occurrences,
    'Probabilities': probabilities
}

# Affiche le tableau
import pandas as pd
df = pd.DataFrame(data_table)
print(df)

    Number  Occurrences  Probabilities
0        1         1047         0.1047
1        2         1035         0.1035
2        3          973         0.0973
3        4         1073         0.1073
4        5         1004         0.1004
5        6          992         0.0992
6        7          972         0.0972
7        8         1046         0.1046
8        9         1002         0.1002
9       10         1087         0.1087
10      11         1054         0.1054
11      12         1056         0.1056
12      13         1021         0.1021
13      14         1035         0.1035
14      15         1025         0.1025
15      16         1051         0.1051
16      17         1016         0.1016
17      18         1000         0.1000
18      19         1017         0.1017
19      20         1002         0.1002
20      21         1013         0.1013
21      22         1000         0.1000
22      23         1040         0.1040
23      24         1027         0.1027
24      25         1029  