# titre

## Exo 1

In [29]:
import numpy as np

a = np.arange(10 +1)
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Exo 2

In [27]:
import numpy as np

a = np.linspace(0, 1, 10)
a


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

## Exo 3

In [31]:
T = np.sum([5,2,8,17,6,14])
T

52

## Exo 4

Le code suivant utilise la fonction numpy.dot() pour calculer le produit scalaire de deux tableaux ou vecteurs en Python.

In [34]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

loulou = np.dot(a, b)
loulou

30

## Exo 6

In [35]:
import numpy as np

a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
sorted_array = np.sort(a)

print("Sorted array: ", sorted_array)

Sorted array:  [ 1  2  2  3  4  6  8  9 23 33 54 54 55 77 86 89]


## Exo 7

In [52]:
import numpy as np

a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
sorted_array = np.min(a)
sorted1 = np.max(a)
sorted2 = np.mean(a)
sorted3 = np.median(a)
sortedT = np.std(a)
print("La valeur min is: ", sorted_array, "--  la valeur max is :", sorted1, "--  La moyenne is: ", sorted2, "--  La mediane is: ", sorted3, "--  l'ecart type is:", sortedT, "ma grosse pucinette"   )



La valeur min is:  1 --  la valeur max is : 89 --  La moyenne is:  31.625 --  La mediane is:  16.0 --  l'ecart type is: 31.557239660654734 ma grosse pucinette


## Exo 8

In [61]:
a = np.array([1,2,55,77,33,54,86,23,89,54,2,3,9,8,6,4])
1*(a>5)


array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0])

la solution est telle => car une codition renvoie forcement un boolean ex: 

a>5 
array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True,  True, False])

Alors que 1*(a>5) renvoie 0 (if la condition est False) et 1 (if la condition est True)

In [59]:
1 * (a>5)

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0])

In [56]:
a[a>5]= 10
a

array([ 1,  2, 10, 10, 10, 10, 10, 10, 10, 10,  2,  3, 10, 10, 10,  4])

## Exo 9

In [67]:
np.random.randint(0,10, size=(3,3))



array([[2, 8, 3],
       [4, 7, 2],
       [4, 7, 8]])